#' Generate txt file with all installed packages
#'
#' @param file_name Character, desired file name as txt
#'
#' @return A txt file named "package_list.txt" saved to your working directory
#' @export
get_packages <- function(file_name) {
  packs <- as.vector(installed.packages()[, 1])
  packs <- paste0('"', packs, '"')
  writeLines(packs, file_name)
}
#' @examples
#' get_packages("package_list.txt")



#' @title Bulk install packages from txt file
#'
#' @param file_path Character, name or file path for the text document generated by `get.packages` function
#'
#' @return Runs a bulk installation of all the packages pulled using `get.packages` function
#' @export
bulk_install <- function(file_path) {
  data <- read.table(file_path, sep = ",", header = FALSE)
  pack_vec <- as.vector(unlist(t(as.matrix(data))))
  install.packages(pack_vec)
}
#' @examples
#' setwd("~/Downloads")
#' bulk_install("package_list.txt")

# Load the required library
library(rstudioapi)

# Define a function to retrieve RStudio global options and save them to a file
save_rstudio_options <- function(file_name) {
  # Get RStudio global options
  options_data <- rstudioapi::getGlobalOptions()

  # Save the options to a file in the working directory
  writeLines(paste(names(options_data), options_data, sep = " = "), file_name)
}

# Call the function with the desired file name
save_rstudio_options("RStudio_Global_Options.txt")
